# ARM base image - this maked the docker image executable on MacOS M1 and Raspberry Pi Cluster. 

FROM arm32v7/node:14.7.0-alpine3.11

RUN mkdir  /opt/slack-endpoint-mon

# Create app directory
WORKDIR /opt/slack-endpoint-mon

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
#COPY package*.json /opt/slack-endpoint-mon/


# Bundle app source
COPY . /opt/slack-endpoint-mon/


#cccRUN npm install
# If you are building your code for production
RUN npm ci --only=production

EXPOSE 3000
CMD [ "npm", "start" ]